### ISSUE TITLE
ImportError: cannot import name 'ModbusRtu'

### ISSUE THREAD

**Issue by candronikos** [stephane/pylibmodbus#14]
Tried this on a raspberry PI using the [RS485 Shield V3 - Raspberry Pi](https://www.sparkfun.com/products/13706)
Already configured the UART pins to disable serial login prompt and to enable the serial hardware.
My code is below:

```python
from pylibmodbus import ModbusRtu

modbus = ModbusRtu(baud=9600)
response = modbus.read_registers(0,1)

print(response)
```

This is the error I get:
```
Traceback (most recent call last):
  File "libmodbus.py", line 1, in <module>
    from pylibmodbus import ModbusRtu
ImportError: cannot import name 'ModbusRtu'
```

**Comment by stephane** [comment]
I'm not able to reproduce the issue with latest release.
